version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ./frontend.Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: ./backend.Dockerfile
    ports:
      - '8000:8000'
    environment:
      - MODEL_PATH=/app/models
      - ENVIRONMENT=production
